### ISSUE TITLE
Could not load the Hybrid_Auth class.

### ISSUE THREAD

**Issue by xaiborweb** [ApacheEx/CodeIgniter-HybridAuth#2]
You could include the contents of the folder third_party so you do not have to use composer and see if it works.

**Comment by ApacheEx** [comment]
First of all, you don't need to include anything, it's already done by `application/libraries/Hybridauth.php`. You have to run `composer install`, it's one of requirement in Hybridauth library

**Comment by moslemfata** [comment]
I have installed hybridauth via composer and then followed the steps given here
https://github.com/ApacheEx/CodeIgniter-HybridAuth
but always got error "Could not load the Hybrid_Auth class"
any solution?
thanks before
