### ISSUE TITLE
LinkedIn problem

### ISSUE THREAD

**Issue by microgroot** [ApacheEx/CodeIgniter-HybridAuth#4]
Guys, You need to change the "fields" in the config -> Providers -> LinkedIn to scope and not fields

**Comment by ApacheEx** [comment]
Hi, this config is just an example how it should look like. 
A `scope` and `fields` are optional for LinkedIn. 
So I have removed it from [here](https://github.com/ApacheEx/CodeIgniter-HybridAuth/blob/master/application/config/hybridauth.php).
