### ISSUE TITLE
Nothing changing after endpoint?hauth.start=Facebook&hauth.time=1530331436

### ISSUE THREAD

**Issue by ltphen** [ApacheEx/CodeIgniter-HybridAuth#5]
Hello ! 
I've a problem with the authentification given by  CodeIgniter-HybridAuth and ... Every time i navigate to window/Facebook(window/providers), i have this page and nothing else happen
![capture](https://user-images.githubusercontent.com/29165365/42121286-bd41a798-7c23-11e8-99fd-6de6ca7b92ef.PNG)

Don't known where the error can come from

**Comment by ApacheEx** [comment]
👋 
you need to use `hauth/window/Facebook` instead of `window/Facebook`

if it still doesn't work, you should create a test repository where it can be reproduced.

**Comment by ltphen** [comment]
yeah thanks , i solve it . it was because the base_url was without the index.php (like domain.com) so all the routes was like domain.com/hauth/window/<provider> instead of domain.com/index.php/hauth/window/<provider> . so in the hauth_endpoint class the native get didn't really work so the last condition is exceute then the open_realm.html is render .

So to solve it, i just add the index.php in the library file i just unpdate the part where we register all the link to /hauth/window to index.php/hauth/window

**Comment by jimithothi** [comment]
Same issue face it please help me :(
