### ISSUE TITLE
please update CodeIgniter-HybridAuth v3.0.0 RC 8

### ISSUE THREAD

**Issue by xaiborweb** [ApacheEx/CodeIgniter-HybridAuth#7]
hello I integrated CodeIgniter-HybridAuth but it is not working properly facebook gives problems.
I was wondering if you could update it with the official version please or upload all the files to just download and use it with composer creates more files I do not understand very well how it works since it creates a vendor folder and does not include anything in third_party

**Comment by ApacheEx** [comment]
I will take care of this soon. Sorry for waiting, tooo much work

**Comment by ApacheEx** [comment]
Done in #12
