### ISSUE TITLE
Linkdin API V2 Api not support

### ISSUE THREAD

**Issue by Hothi-Jimit** [ApacheEx/CodeIgniter-HybridAuth#8]
Hello sir,

your application too good all are working perfectly. but your linkdin api V1 support so please migrate to V2 its would be great.

Thank You :)

**Comment by ApacheEx** [comment]
this is already fixed in main hybridauth repository for v3 and will be soon fixed for v2. So, pls keep an eye on realese notes

and thank you for your feedback;)
