### ISSUE TITLE
When I'm click on providers then I'm getting this error

### ISSUE THREAD

**Issue by RiteshSinghApache** [ApacheEx/CodeIgniter-HybridAuth#9]
HybridAuth
Open Source Social Sign On PHP Library. 
hybridauth.sourceforge.net/

**Comment by RiteshSinghApache** [comment]
Please reply as soon as possible or please give me the complete configuration for this new version of hybridauth and setup also.

**Comment by ApacheEx** [comment]
`"base_url" => "/hauth/endpoint",` - I checked your example code and it looks like this line is unnecessary from the `config/hybridauth.php`. Please remove it.

**Comment by RiteshSinghApache** [comment]
Ok I removed  "base_url" => "/hauth/endpoint"  from config/hybridauth.php file  but, I'm feshing same problem.

**Comment by ApacheEx** [comment]
describe your steps how can I reproduce it, what you do as first step, second, etc...

**Comment by RiteshSinghApache** [comment]
Steps are as follow,
1> go to the C:\wamp64\www\hybridauthSocial and run the following command:
composer require hybridauth/hybridauth
2> then, go to application/config.php and set composer_autoload to TRUE:
$config['composer_autoload'] = TRUE;
3> download HybridAuth library
4> unpack the library into application/third_party/hybridauth folder
5> run composer install in the library directory (application/third_party/hybridauth)
6> copy these files into my project directory.
    application/config/hybridauth.php
    application/libraries/Hybridauth.php
    application/controllers/Hauth.php
    application/views/hauth
7> Then create a LinkedIn app and give the redirect URL http://localhost/hybridauthSocial/hauth/endpoint?hauth.start=LinkedIn
and run the application .

**Comment by ApacheEx** [comment]
1-7 is clear. But what next? I mean which page you open when `run the application.`

**Comment by RiteshSinghApache** [comment]
1> Give the Linkedin app id and secret key in the config/hybridauth.php file.

2> When I'm run my project by hitting this URL http://localhost/hybridauthSocial/ 
a> then the Hauth/index function is run and view all the provider's list.
![image](https://user-images.githubusercontent.com/25532133/59347549-93db1300-8d32-11e9-9748-3f6468749828.png)

b> then I click to Linkedin it redirects to this page.

![image](https://user-images.githubusercontent.com/25532133/59347640-cb49bf80-8d32-11e9-9046-ec41d13e8da8.png)

**Comment by RiteshSinghApache** [comment]
Please, sir, reply to the above query.

**Comment by RiteshSinghApache** [comment]
Thanks, sir but I solve this error 
(HybridAuth
Open Source Social Sign On PHP Library.
hybridauth.sourceforge.net/)

I'd changed $config['base_url'] in the application\libraries\hybridauth.php file 
$config['base_url'] = $this->CI->config->site_url('hauth/endpoint'); to this
$config['base_url'] = $this->CI->config->site_url('index.php/hauth/endpoint'); or
$config['base_url'] = $this->CI->config->base_url('index.php/hauth/endpoint');

**Comment by ApacheEx** [comment]
coool, I will adapt changes in this repo
